config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"
  put "account", to: "users#update"
  get "account", to: "users#edit"
  delete "account", to: "users#destroy"
  resources :confirmations, only: [:create, :edit, :new], param: :confirmation_token
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  get "login", to: "sessions#new"
  resources :passwords, only: [:create, :edit, :new, :update], param: :password_reset_token
  resources :active_sessions, only: [:destroy] do
    collection do
      delete "destroy_all"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAuthenticationFromScratch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header style="width: 1200px; margin: 0 auto;">
      <% flash.each do |message_type, message| %>
        <div class="<%= message_type %>"><%= message %></div>
      <% end %>
      <ul>
        <% if user_signed_in? %>
          <li><%= link_to "My Account", account_path %></li>
           <li><%= button_to "Logout", logout_path, method: :delete %></li>
        <% else %>
           <li><%= link_to "Login", login_path %></li>
           <li><%= link_to "Sign Up", sign_up_path %></li>
           <li><%= link_to "Forgot my password", new_password_path %></li>
           <li><%= link_to "Didn't receive confirmation instructions", new_confirmation_path %></li>
        <% end %>
      </ul>
      <hr/>
    </header>
    <main style="width: 1200px; margin: 0 auto;"> 
      <%= yield %>
    </main>
  </body>
</html>